@url=http://localhost:3066

### GET base route
GET {{url}}

### GET Jobs route
GET {{url}}/jobs

### GET skills route
GET {{url}}/skills


// lowdb
### GET a job
GET {{url}}/jobsLowdb/3
### DELETE a job
DELETE {{url}}/jobsLowdb/3


